package com.molohala.grow.designsystem.foundation.color

import androidx.compose.ui.graphics.Color

fun lightColorScheme() = GrowColorScheme(
    textNormal = GrowPallete.Neutral90,
    textDarken = GrowPallete.Neutral80,
    textAlt = GrowPallete.Neutral50,
    textInverse = GrowPallete.Neutral10,
    textDisabled = GrowPallete.Neutral40,
    textWarning = GrowPallete.Red70,
    buttonPrimary = GrowPallete.Primary60,
    buttonPrimaryPressed = GrowPallete.Primary80,
    buttonPrimaryDisabled = GrowPallete.Neutral10,
    buttonText = GrowPallete.Neutral90,
    buttonTextDisabled = GrowPallete.Neutral40,
    background = GrowPallete.Neutral00,
    backgroundAlt = GrowPallete.Neutral10,
    backgroundInverse = GrowPallete.Neutral80,
    github = Color(0xFF24292E),
    baekjoon = Color(0xFF0076C0),
    dividerNormal = GrowPallete.Neutral20,
    textFieldIcon = GrowPallete.Neutral90,
    textFieldPrimary = GrowPallete.Primary80,
    textFieldSecondary = GrowPallete.Neutral30,
    textFieldSecondaryDisabled = GrowPallete.Neutral30,
    textFieldTextDisabled = GrowPallete.Neutral40,
    avatarLabel = GrowPallete.Neutral30,
    avatarBackground = GrowPallete.Neutral20,
    elevationBlack1 = GrowPallete.Neutral100,
    elevationBlack2 = GrowPallete.Neutral100,
    elevationBlack3 = GrowPallete.Neutral100,
    bottomTabPrimary = GrowPallete.Neutral70,
    bottomTabPrimaryDisabled = GrowPallete.Neutral40,
    bottomTabSecondary = GrowPallete.Neutral30,
    likePrimary = GrowPallete.Red60,
    likeSecondary = GrowPallete.Red10
)

fun darkColorScheme() = GrowColorScheme(
    textNormal = GrowPallete.Neutral10,
    textDarken = GrowPallete.Neutral50,
    textAlt = GrowPallete.Neutral60,
    textInverse = GrowPallete.Neutral10,
    textDisabled = GrowPallete.Neutral40,
    textWarning = GrowPallete.Red60,
    buttonPrimary = GrowPallete.Primary60,
    buttonPrimaryPressed = GrowPallete.Primary80,
    buttonPrimaryDisabled = GrowPallete.Neutral70,
    buttonText = GrowPallete.Neutral90,
    buttonTextDisabled = GrowPallete.Neutral60,
    background = GrowPallete.Neutral80,
    backgroundAlt = GrowPallete.Neutral90,
    backgroundInverse = GrowPallete.Neutral00,
    github = GrowPallete.Neutral10,
    baekjoon = GrowPallete.Neutral10,
    dividerNormal = GrowPallete.Neutral70,
    textFieldIcon = GrowPallete.Neutral60,
    textFieldPrimary = GrowPallete.Primary80,
    textFieldSecondary = GrowPallete.Neutral70,
    textFieldSecondaryDisabled = GrowPallete.Neutral70,
    textFieldTextDisabled = GrowPallete.Neutral70,
    avatarLabel = GrowPallete.Neutral80,
    avatarBackground = GrowPallete.Neutral70,
    elevationBlack1 = Color(0xFFCCCCD6),
    elevationBlack2 = Color(0xFFCCCCD6),
    elevationBlack3 = Color(0xFFCCCCD6),
    bottomTabPrimary = GrowPallete.Primary40,
    bottomTabPrimaryDisabled = GrowPallete.Neutral60,
    bottomTabSecondary = GrowPallete.Neutral70,
    likePrimary = GrowPallete.Red60,
    likeSecondary = GrowPallete.Transparent
)