package com.molohala.grow.designsystem.foundation.color

import androidx.compose.ui.graphics.Color

fun lightColorScheme() = GrowColorScheme(
    textNormal = GrowPallete.Neutral90,
    textDarken = GrowPallete.Neutral80,
    textAlt = GrowPallete.Neutral50,
    textInverse = GrowPallete.Neutral10,
    textDisabled = GrowPallete.Neutral40,
    buttonPrimary = GrowPallete.Primary60,
    buttonPrimaryDisabled = GrowPallete.Primary80,
    buttonText = GrowPallete.Neutral90,
    buttonTextDisabled = GrowPallete.Neutral40,
    background = GrowPallete.Neutral00,
    backgroundAlt = GrowPallete.Neutral10,
    backgroundInverse = GrowPallete.Neutral80,
    github = Color(0xFF24292E),
    baekjoon = Color(0xFF0076C0),
    dividerNormal = GrowPallete.Neutral20,
    textFieldIcon = GrowPallete.Neutral90,
    textFieldPrimary = GrowPallete.Primary80,
    textFieldSecondary = GrowPallete.Neutral30,
    textFieldSecondaryDisabled = GrowPallete.Neutral30,
    textFieldTextDisabled = GrowPallete.Neutral40,
    avatarLabel = GrowPallete.Neutral30,
    avatarBackground = GrowPallete.Neutral20,
    elevationBlack1 = GrowPallete.Neutral100.copy(alpha = 0.02f * 255),
    elevationBlack2 = GrowPallete.Neutral100.copy(alpha = 0.04f * 255),
    elevationBlack3 = GrowPallete.Neutral100.copy(alpha = 0.06f * 255),
    bottomTabPrimary = GrowPallete.Neutral70,
    bottomTabPrimaryDisabled = GrowPallete.Neutral40,
    bottomTabSecondary = GrowPallete.Neutral30,
    likePrimary = GrowPallete.Red60,
    likeSecondary = GrowPallete.Red10
)


fun darkColorScheme() = GrowColorScheme(
    textNormal = GrowPallete.Neutral90,
    textDarken = GrowPallete.Neutral80,
    textAlt = GrowPallete.Neutral50,
    textInverse = GrowPallete.Neutral10,
    textDisabled = GrowPallete.Neutral40,
    buttonPrimary = GrowPallete.Primary60,
    buttonPrimaryDisabled = GrowPallete.Primary80,
    buttonText = GrowPallete.Neutral90,
    buttonTextDisabled = GrowPallete.Neutral40,
    background = GrowPallete.Neutral00,
    backgroundAlt = GrowPallete.Neutral10,
    backgroundInverse = GrowPallete.Neutral80,
    github = Color(0xFF24292E),
    baekjoon = Color(0xFF0076C0),
    dividerNormal = GrowPallete.Neutral20,
    textFieldIcon = GrowPallete.Neutral90,
    textFieldPrimary = GrowPallete.Primary80,
    textFieldSecondary = GrowPallete.Neutral30,
    textFieldSecondaryDisabled = GrowPallete.Neutral30,
    textFieldTextDisabled = GrowPallete.Neutral40,
    avatarLabel = GrowPallete.Neutral30,
    avatarBackground = GrowPallete.Neutral20,
    elevationBlack1 = GrowPallete.Neutral100.copy(alpha = 0.02f * 255),
    elevationBlack2 = GrowPallete.Neutral100.copy(alpha = 0.04f * 255),
    elevationBlack3 = GrowPallete.Neutral100.copy(alpha = 0.06f * 255),
    bottomTabPrimary = GrowPallete.Neutral70,
    bottomTabPrimaryDisabled = GrowPallete.Neutral40,
    bottomTabSecondary = GrowPallete.Neutral30,
    likePrimary = GrowPallete.Red60,
    likeSecondary = GrowPallete.Red10
)